services:

  file_ingester:
      build:
        context: .
        dockerfile: file_ingester.Dockerfile
      environment:
        - NEO4J_URI=${NEO4J_URI-neo4j://database:7687}
        - NEO4J_PASSWORD=${NEO4J_PASSWORD-password}
        - NEO4J_USERNAME=${NEO4J_USERNAME-neo4j}
        - OPENAI_API_KEY=${OPENAI_API_KEY-}
        - GOOGLE_API_KEY=${GOOGLE_API_KEY-}
        - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
        - LLM=${LLM-llama2}
        - EMBEDDING_MODEL=${EMBEDDING_MODEL-sentence_transformer}
        - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT-"https://api.smith.langchain.com"}
        - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2-false}
        - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
        - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      networks:
        - net
      depends_on:
        database:
          condition: service_healthy
        pull-model:
          condition: service_completed_successfully
      ports:
        - 8503:8503